[package]
name = "complexpr"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num-complex = "0.4.1"
num-rational = "0.4.0"
num-traits = "0.2.15"
rustyline = "10.0.0"
backtrace = "0.3.66"
