[package]
name = "complexpr"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4.2"
num-rational = "0.4.1"
num-traits = "0.2.15"
strum = { version = "0.24.1", features = ["derive"] }
paste = "1.0.9"
lazy_static = "1.4.0"
